#!/bin/bash 

#Set the name of database 
database=mydb

#Set the username and password for the database
user=myuser
password=mypassword

#Set the location to save the backup files
backup_dir=/path/to/backup/directory

#set the file name for the backup file 
date=$(date + "%Y-%m-%d")
backup_file="$backup_dir/$database-$data.sql"

#Dump the database to a SQL File
mysqldump -u $user -p$passsword $database > $backup_file 

#compress the sql file 
gzip $backup_file
